apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-docker-certs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-docker
spec:
  selector:
    matchLabels:
      run: jenkins-docker
  replicas: 1
  template:
    metadata:
      labels:
        run: jenkins-docker
    spec:
      containers:
        - name: jenkins-docker
          image: docker:dind
          env:
            - name: DOCKER_TLS_CERTDIR
              value: "/certs"
          volumeMounts:
            - mountPath: "/certs/client"
              name: jenkins-docker-certs
          securityContext:
            privileged: true
          ports:
            - containerPort: 2376
      volumes:
        - name: jenkins-docker-certs
          persistentVolumeClaim:
            claimName: jenkins-docker-certs
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-data
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-docker
  labels:
    run: jenkins-docker
spec:
  type: NodePort
  ports:
    - port: 2376
      targetPort: 2376
      protocol: TCP
  selector:
    run: jenkins-docker