apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-docker-certs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi